### ISSUE TITLE
Release for magnolia 0.14.x

### ISSUE THREAD

**Issue by kubukoz** [spotify/magnolify#104]
Hi! Could you make a release of the library (especially the scalacheck module) compiled with a Magnolia release in the 0.14 line? Thanks for the cool library set!

**Comment by nevillelyh** [comment]
Hi good timing, was planning to release tomorrow :)

**Comment by kubukoz** [comment]
Nice! I'd love to start using it and deprecate an internal thing we made :)

**Comment by nevillelyh** [comment]
And it's released, might take a while to show up in Maven.

**Comment by kubukoz** [comment]
Thanks!
