### ISSUE TITLE
camelCase/PascalCase/snake_case/kebab-case mapper

### ISSUE THREAD

**Issue by nevillelyh** [spotify/magnolify#141]
Avro, BigQuery, etc. uses `snake_case` internally while `camelCase` is more idiomatic Scala.
Some users requested case conversion to be supported.

Two possible options:

1. Add an extra parameter to all `*Type` converters, i.e. a bijection between internal (Avro, BQ, etc.) and Scala cases. Something like `val at = AvroType[MyRecord](Case.Snake, Case.Camel)`.

However we should make sure the mappings are 1-to-1 and there's no conflicts.

2. Add independent mappers of `GenericRecord => GenericRecord`, `TableRow => TableRow`, essentially making a copy of the record by renaming all the fields, before feeding it into the converters.

This is more decoupled but adds more overhead and possibly more complexity and is less reusable across converters. In the case of Avro & BQ, we need to re-map schema as well. In the case of Avro, `GenericRecord` is an interface so we can possibly return a lazy view that wraps another `GenericRecord` (in `neville/mapper2` branch), but I ended up doing more hacky stuff to get it to behave like a real `GenericRecord`.

2 WIP branches for `GenericRecord` mapping, one making copies and one lazy view.
https://github.com/spotify/magnolify/tree/neville/mapper
https://github.com/spotify/magnolify/tree/neville/mapper2

**Comment by syodage** [comment]
@nevillelyh came up an implementation for #1 https://github.com/spotify/magnolify/tree/shameera/filed_name_mapping

Couldn't see a better way to bake this into `trait Converter`. if we go this path, we have to update the all necessary *Type. 

```scala
case class Track(trackId: Int, trackName: String)
val aft = AvroType[Track](toSnakeCase)
```

![Screen Shot 2020-06-08 at 12 26 04 PM](https://user-images.githubusercontent.com/3529221/84056073-b45c9e00-a983-11ea-8ec1-375dfe9782bd.png)

**Comment by nevillelyh** [comment]
New WIP branch: https://github.com/spotify/magnolify/tree/case-mapper

**Comment by nevillelyh** [comment]
Did some basic benchmark. Mostly Ok but `AvroBench.avroTo` seems way off.

master:

```[info] Benchmark                     Mode  Cnt      Score     Error  Units
[info] AvroBench.avroFrom            avgt   10   1968.186 ±  99.247  ns/op
[info] AvroBench.avroSchmea          avgt   10   6843.803 ± 115.318  ns/op
[info] AvroBench.avroTo              avgt   10  72808.144 ± 881.913  ns/op
[info] TableRowBench.tableRowFrom    avgt   10   9746.518 ± 174.121  ns/op
[info] TableRowBench.tableRowSchema  avgt   10  23132.630 ± 276.478  ns/op
[info] TableRowBench.tableRowTo      avgt   10  11080.110 ± 153.466  ns/op
```

`identity` mapper:

```[info] Benchmark                     Mode  Cnt       Score       Error  Units
[info] AvroBench.avroFrom            avgt   10    1942.699 ±    47.263  ns/op
[info] AvroBench.avroSchmea          avgt   10    6834.892 ±   155.658  ns/op
[info] AvroBench.avroTo              avgt   10  273955.338 ± 25053.639  ns/op
[info] TableRowBench.tableRowFrom    avgt   10    9822.360 ±   129.232  ns/op
[info] TableRowBench.tableRowSchema  avgt   10   22818.333 ±   192.875  ns/op
[info] TableRowBench.tableRowTo      avgt   10   11765.242 ±    83.626  ns/op
```

**Comment by nevillelyh** [comment]
After adding schema cache:

```
[info] Benchmark                     Mode  Cnt      Score     Error  Units
[info] AvroBench.avroFrom            avgt    5   1736.875 ±  30.571  ns/op
[info] AvroBench.avroSchmea          avgt    5   6780.416 ± 223.390  ns/op
[info] AvroBench.avroTo              avgt    5   5370.960 ± 323.343  ns/op
[info] TableRowBench.tableRowFrom    avgt    5  10015.674 ± 407.268  ns/op
[info] TableRowBench.tableRowSchema  avgt    5  22828.502 ± 564.830  ns/op
[info] TableRowBench.tableRowTo      avgt    5  11300.360 ± 308.394  ns/op
```
