### ISSUE TITLE
BigtableType field names shortening

### ISSUE THREAD

**Issue by stormy-ua** [spotify/magnolify#287]
Bigtable column qualifiers are [stored as data](https://cloud.google.com/bigtable/docs/schema-design#columns) for each cell, so the best option is to keep column names as short as possible. At the same time, in a user case class field names are supposed to be long enough to convey field designation. It would be great to annotate case class fields with an attribute having a shortened field name e.g.:

```scala
case class MyClass(@btfieldname("f") superDescriptiveField: String)
```

I was thinking about adding implicit ClassTag to the BigtableType apply function and use reflection to traverse the type and build fields map once and cache it. Wondering if there are any other thoughts how to do this.

**Comment by nevillelyh** [comment]
This you can do already by abusing `CaseMapper`?
https://github.com/spotify/magnolify/blob/master/docs/bigtable.md

**Comment by stormy-ua** [comment]
Yes :) I was thinking about renaming `CaseMapper` to `FieldNameMapper`. Oh nice, I didn't know magnolia supports annotations. Thanks for the hint!

**Comment by nevillelyh** [comment]
You're right, `CaseMapper` is misleading since you can do whatever to the string 😭

**Comment by nevillelyh** [comment]
Closing as won't fix.
