### ISSUE TITLE
AvroType to produce a SpecificRecordBase instead of GenericRecord 

### ISSUE THREAD

**Issue by SemanticBeeng** [spotify/magnolify#402]
Trying to use `magnolify-avro` with Lightbend `Cloudflow` and their Avro based logic depends on SpecificRecordBase implementations auto-generated from avsc. 

Would it be possible to generate such a type dynamically ?

cc @nevillelyh

**Comment by nevillelyh** [comment]
It's theoretically possibly but would be way too much work and complexity, e.g. calling Avro compiler on a Magnolify derived schema at runtime, compiling the result `.java` `SpecificRecord` and loading into the classpath.

For cases requiring `SpecificRecord` we prefer to use `.avsc` as the source of truth.

**Comment by nevillelyh** [comment]
Gonna close this as a won't fix. Feel free to reopen if you have better ideas.
