### ISSUE TITLE
Avro 1.8 support?

### ISSUE THREAD

**Issue by anne-decusatis** [spotify/magnolify#53]
https://avro.apache.org/docs/current/api/java/org/apache/avro/Schema.Field.html#NULL_DEFAULT_VALUE is used in AvroType conversions, and is new in Avro 1.9.x. (Note that there's no mention of it in https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/Schema.Field.html)

I want to use this conversion in a project which is already using Avro 1.8. Is it possible to add support for this?

**Comment by nevillelyh** [comment]
Can you use this?
https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/JsonProperties.html#NULL_VALUE

Note that most third-party deps in this project are "Provided". This is intentional so users can depend on versions they prefer. We just need to be cautious when using API only in certain versions.

**Comment by anne-decusatis** [comment]
@nevillelyh my project is throwing a NoSuchFieldError exception on https://github.com/spotify/magnolify/blob/master/avro/src/main/scala/magnolify/avro/AvroType.scala#L150 - can we drop in NULL_VALUE there?

**Comment by nevillelyh** [comment]
Good catch, yeah I think so.

To actually implement the decoupling I mentioned we need to parameterize these dependency versions and cover them in the CI matrix. Probably an overkill though for now.
https://github.com/nevillelyh/protobuf-generic/blob/master/.travis.yml

**Comment by nevillelyh** [comment]
@anne-decusatis wanna do a quick PR to revert to the 1.8 `JsonProperties.NULL_VALUE`? We can fix the cross version test coverage in a separate PR.
